version: "2.0"

dependencies: ./project-dependencies.yaml

default:
  build-command:
    upstream: mvn -e --builder smart -T1C clean install -DskipTests -Dgwt.compiler.skip=true -Dgwt.skipCompilation=true -Denforcer.skip=true -Dcheckstyle.skip=true -Dspotbugs.skip=true -Drevapi.skip=true -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3

build:
  - project: kiegroup/optaplanner
    build-command:
      upstream: mvn -e clean install -Dquickly -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3

  - project: kiegroup/optaplanner-quickstarts
    build-command:
      upstream: mvn -e -nsu -Dfull clean install -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3

  - project: jboss-integration/kogito-rhba
    build-command:
      current: mvn -e --builder smart -T1C clean install -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3
    archive-artifacts:
      path: |
        **/**kogito**.zip
