name: Build Chain Generate Files

on: [pull_request]

jobs:
  build-chain:
    runs-on: ubuntu-latest
    name: File Generation
    steps:
      - uses: actions/checkout@v2
        if: github.event_name == 'pull_request'
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/checkout@v2
        if: github.event_name == 'push'
        with:
          fetch-depth: 0
      - name: Image Generation
        uses: kiegroup/build-chain-files-generator@v1.0
        with:
          definition-file: .ci/pull-request-config.yaml
          file-type: image
          output-file-path: ./docs/project-dependencies-hierarchy.png
      - name: Repository List Generation
        uses: kiegroup/build-chain-files-generator@v1.0
        with:
          definition-file: .ci/pull-request-config.yaml
          file-type: repository-list
          output-file-path: ./script/repository-list.txt
      - name: Push Changes
        run: |
          git config user.name "kiegroup"
          git config user.email "kiegroup@redhat.com"
          git add ./docs/project-dependencies-hierarchy.png ./script/repository-list.txt
          git commit -m "[Build Chain Generate Files] project hierarchy files updated"
          git push
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: generated-files
          path: |
            **/project-dependencies-hierarchy.png
            **/repository-list.txt          
