name: On create branch action

on:
  create:
    branches-ignore:
      - generate_files/*
      - dependabot/*
      - new_branch_action/*

jobs:
  adapt-generate-files:
    runs-on: ubuntu-latest
    name: Adapt generate_files
    steps:
      - uses: actions/checkout@v2
      - name: print current branch
        run: echo ${GITHUB_REF##*/}
      - name: Add branch to generate_files.yml
        run: sed -i "6i \ \ \ \ \ \ \- ${GITHUB_REF##*/}" ./.github/workflows/generate_files.yml
      - name: Add Changes
        run: git add ./.github/workflows/generate_files.yml -f
      - name: Set branch name
        run: echo "BRANCH_NAME_FLOW=new_branch_action/$(date +'%Y%m%dT%H%M%S')" >> $GITHUB_ENV          
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_ACTION_PERSONAL_TOKEN }}
          commit-message: Update generate_files.yml
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: ${{ env.BRANCH_NAME_FLOW }}
          delete-branch: true
          title: '[New Branch Created] Update generate_files.yml.'
          body: |
            # Update Report
            Branch ${GITHUB_REF##*/} added to ./.github/workflows/generate_files.yml
          draft: false
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
